
// const mongoose = require('mongoose');
import mongoose from 'mongoose';


    
    
   
    


function GetUser(){


// this use here is an array that is returned from db
User.find(function(err,use){ 
    if(err){
        console.log(err);
    }else{
    console.log(use);
    
    
    fruits.forEach(function(us){
        console.log(us.name);
    });
    
    }
    
    });

};



function SaveUser(name1,email1,Birthday1,Phonenumber1, password1){


     mongoose.connect("mongodb://localhost:27017/Users", {useNewUrlParser :true});
    
    
    
    const UserSchema = new  mongoose.Schema({
        Name: String,
        // rating : {
        //     type: Number,
        //     min: [0, 'Too few eggs'],   // these are validation of mongoose
        //     max: 10
        //   },
        Email: String,
        Birthday: Date, 
        Number: String,
        Password: String,
      });
    
    const User =mongoose.model("User", UserSchema);  // User collection
    
    
   



    const row1 = new User({   
        name: name1,
        Email : email1,
        Birthday: Birthday1,
        Number: Phonenumber1,
        Password:password1
    });
    
    row1.save();  //for saving a single value

};










/*
Fruit.insertMany([orange,melon],function(err){
    if(err){
        console.log(err);

    }else{
        console.log("Successfully saved all the fruits to fruitDb");
    }
});

*/


// now we will learn how to  get from database






// now we will se how to update a db we will fetch a record on the basis of id that was generated by db


function SearchUser(num){
Fruit.updateOne({ Number:num},function(err){
    if(err){
        console.log(err);
    }else{
    console.log("Successfully updated the document.");
    }
});

};


 function DeleteUser(num){

// now we will see how to delete a row from table

User.deleteOne({Number:num },function(err){
    if(err){
        console.log(err);
    }else{
    console.log("Successfully deleted from the document.");
    }
});

};

//  export default {SaveUser,DeleteUser,GetUser,SearchUser} ;
export default SaveUser;
